[[language]]
name = "toml"
file-types = ["toml", { glob = "*.toml.tmpl"}]

[[language]]
name = "hyprlang"
file-types = [{ glob = "hypr/*.conf"}]

[[language]]
name = "lua"
file-types = ["lua", { glob = "*.lua.tmpl" }]
roots = [".luarc.json", ".luarc.jsonc"]

[[language]]
name = "git-config"
file-types = ["gitconfig", {glob = "dot_gitconfig"}, {glob = "dot_gitconfig.tmpl"}, { glob = ".gitmodules" }, { glob = "gitconfig" }, { glob = ".gitconfig" }, { glob = ".git/config" }, { glob = ".config/git/config" }, { glob = ".git/modules/*/config" }, { glob = "config.worktree" }]
